[database]
# Адрес сервера на котором находится БД.
host = localhost
# Имя пользователя.
user = root
# Пароль пользователя. Если пароля нет, оставьте пустым.
password = 
# Название БД для подключения.
name = shop

[table]
# Количество столбцов выходной таблицы
columns = 2
# Имена колонок в формате: names = column1, column2, ...
names = id, username